# Generated by Django 5.2.8 on 2025-11-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Estudiante',
        ),
    ]
